name: notifier_builder
description: A Flutter Builder for Notifiers
version: 0.1.0-beta
repository: https://github.com/MelbourneDeveloper/notifier_builder

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  austerity: ^0.0.10-beta
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
